<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ytx.ai</groupId>
        <artifactId>ytx-agent-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ytx-agent-framework-workflow</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>
        <dependency>
            <groupId>com.ytx.ai</groupId>
            <artifactId>ytx-agent-framework-sandbox</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.ytx.ai</groupId>
            <artifactId>ytx-agent-framework-dao</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.ytx.ai</groupId>
            <artifactId>ytx-agent-framework-llm</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.gitee.jd-platform-opensource</groupId>
            <artifactId>asyncTool</artifactId>
            <version>V1.4-79651da39d-1</version>
        </dependency>

    </dependencies>


    <repositories>
        <repository>
            <id>ali maven</id>
            <url>https://maven.aliyun.com/repository/central</url>
        </repository>
        <repository>
            <id>scijava</id>
            <url>https://maven.scijava.org/content/repositories/public/</url>
        </repository>
    </repositories>
</project>